### ISSUE TITLE
Where to get version 0.2.0?

### ISSUE THREAD

**Issue by ryan-williams** [ASIDataScience/scala-plotly-client#31]
[It's not on Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cplotly).

**Comment by pbugnion** [comment]
There seems to be an issue syncing with Maven Central. I've raised a ticket but, in the meantime, you can download it from Sonatype:

```
scalaVersion := "2.11.8"

resolvers += Resolver.sonatypeRepo("public")

libraryDependencies += "co.theasi" %% "plotly" % "0.2.0"
```

**Comment by srstevenson** [comment]
This [is fixed](https://search.maven.org/#artifactdetails%7Cco.theasi%7Cplotly_2.11%7C0.2.0%7Cjar) now.
